export { scrollToTop } from './scrollToTop'
export { applyDiscount } from './applyDiscount'
export { sortingOptions } from './sortingOptions'
export { getErrorMessage } from './getErrorMessage'
export { calculateCartTotals } from './cartHelper'
export { formatPrice } from './applyDiscount'