export { scrollToTop } from './scrollToTop'
export { applyDiscount } from './priceHelper'
export { sortingOptions } from './sortingOptions'
export { getErrorMessage } from './getErrorMessage'
export { calculateCartTotals } from './cartHelper'
export { formatPrice } from './priceHelper'
export { HAPTIC_PRESETS } from './hapticPresets'